//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MAHD { get; set; }
        public int MADATPHONG { get; set; }
        public string GHICHU { get; set; }
        public int Id { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
