//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatDichVu
    {
        public int MADATPHONG { get; set; }
        public int MADV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public System.DateTime ngayDung { get; set; }
        public Nullable<double> giaDichVuHienTai { get; set; }
        public int Id { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
