//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViec
    {
        public int MALICHLAMVIEC { get; set; }
        public System.DateTime NGAYLAMVIEC { get; set; }
        public string BUOI { get; set; }
        public int MANHANVIEN { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
