//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string TENTAIKHOAN { get; set; }
        public string PASS { get; set; }
        public Nullable<int> MACHUCVU { get; set; }
        public Nullable<int> MANHANVIEN { get; set; }
        public Nullable<bool> isBan { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
